---
convnext_tiny:
  stats:
    parameters: 44.6 # million
    gmacs: 4.5
    top1: 82.90
    top5: 96.62
  model:
    _target_: eflbench.models.BenchModel
    build:
      _target_: timm.create_model
      model_name: convnext_tiny.fb_in22k_ft_in1k
      num_classes: ${dataset.num_classes}
    finetune_keys: [model.head.norm.weight,
                    model.head.norm.bias,
                    model.head.fc.weight,
                    model.head.fc.bias]
