---
convnext_small:
  stats:
    parameters: 66.3 # million
    gmacs: 8.7
    top1: 84.56
    top5: 97.394
  model:
    _target_: eflbench.models.BenchModel
    build:
      _target_: timm.create_model
      model_name: convnext_small.fb_in22k_ft_in1k
      num_classes: ${dataset.num_classes}
    finetune_keys: [model.head.norm.weight,
                    model.head.norm.bias,
                    model.head.fc.weight,
                    model.head.fc.bias]
