---
edgenext_small:
  stats:
    parameters: 5.6 # million
    gmacs: 1.3 # for 256x256 inputs
    top1: 79.41 # from paper
  model:
    _target_: eflbench.models.BenchModel
    build:
      _target_: timm.create_model
      model_name: edgenext_small
      num_classes: ${dataset.num_classes}
    finetune_keys: [model.head.norm.weight,
                    model.head.norm.bias,
                    model.head.fc.weight,
                    model.head.fc.bias]
