---
efficientnet_b1:
  stats:
    parameters: 7.8 # million
    gmacs: 0.6
    top1: 79.1
    top5: 94.4
  model:
    _target_: eflbench.models.BenchModel
    build:
      _target_: timm.create_model
      model_name: efficientnet_b1
      num_classes: ${dataset.num_classes}
    finetune_keys: [model.classifier.weight,
                    model.classifier.bias]