---
efficientvit_b1:
  stats:
    parameters: 9.1 # M
    gmacs: 0.5
    top1: 79.39 # from table in repo
    top5: 94.35
  model:
    _target_: eflbench.models.BenchModel
    build:
      _target_: timm.create_model
      model_name: efficientvit_b1.r224_in1k
      num_classes: ${dataset.num_classes}
    finetune_keys: [model.head.in_conv.conv.weight,
                    model.head.in_conv.norm.weight,
                    model.head.in_conv.norm.bias,
                    model.head.classifier.0.weight,
                    model.head.classifier.1.weight,
                    model.head.classifier.1.bias,
                    model.head.classifier.4.weight,
                    model.head.classifier.4.bias]
