---
efficientformer_l1:
  stats:
    parameters: 12.3 # million
    gmacs: 1.3
    top1: 80.50
    top5: 94.99
  model:
    _target_: eflbench.models.BenchModel
    build:
      _target_: timm.create_model
      model_name: efficientformer_l1
      num_classes: ${dataset.num_classes}
    finetune_keys: [model.norm.weight,
                    model.norm.bias,
                    model.head.weight,
                    model.head.bias,
                    model.head_dist.weight,
                    model.head_dist.bias]
