---
ghostnetv2_100:
  stats:
    parameters: 6.2 # million
    gmacs: 0.2
    top1: 75.17
    top5: 92.35
  model:
    _target_: eflbench.models.BenchModel
    build:
      _target_: timm.create_model
      model_name: ghostnetv2_100
      num_classes: ${dataset.num_classes}
    finetune_keys: [model.conv_head.weight,
                    model.conv_head.bias,
                    model.classifier.weight,
                    model.classifier.bias]
