---
mobilenetv2_050:
  stats:
    parameters: 2.0 # million
    gmacs: 0.1
    top1: 65.95  # from timm results-imagenet.csv
    top5: 86.08
  model:
    _target_: eflbench.models.BenchModel
    build:
      _target_: timm.create_model
      model_name: mobilenetv2_050.lamb_in1k
      num_classes: ${dataset.num_classes}
    finetune_keys: [model.classifier.weight, model.classifier.bias]
