---
mobilevitv2_050:
  stats:
    parameters: 1.4 # million
    gmacs: 0.5 # image size 256x256
    top1: 70.2 # from paper
  model:
    _target_: eflbench.models.BenchModel
    build:
      _target_: timm.create_model
      model_name: mobilevitv2_050
      num_classes: ${dataset.num_classes}
    finetune_keys: [model.head.fc.weight, model.head.fc.bias]