---
swin_small:
  stats:
    parameters: 49.6 # million
    gmacs: 8.8
    top1: 83.21 # from timm results-imagenet.csv
    top5: 96.32
  model:
    _target_: eflbench.models.BenchModel
    build:
      _target_: timm.create_model
      model_name: swin_small_patch4_window7_224
      num_classes: ${dataset.num_classes}
    finetune_keys: [model.norm.weight,
                    model.norm.bias,
                    model.head.fc.weight,
                    model.head.fc.bias]
