---
swin_base:
  stats:
    parameters: 87.8 # million
    gmacs: 15.5
    top1: 83.61 # from timm results-imagenet.csv
    top5: 96.45
  model:
    _target_: eflbench.models.BenchModel
    build:
      _target_: timm.create_model
      model_name: swin_base_patch4_window7_224
      num_classes: ${dataset.num_classes}
    finetune_keys: [model.norm.weight,
                    model.norm.bias,
                    model.head.fc.weight,
                    model.head.fc.bias]
