---
vit_tiny:
  stats:
    parameters: 5.7 # million
    gmacs: 1.1
    top1: 75.46 # from timm results-imagenet.csv
    top5: 92.84
  model:
    _target_: eflbench.models.BenchModel
    build:
      _target_: timm.create_model
      model_name: vit_tiny_patch16_224.augreg_in21k_ft_in1k
      num_classes: ${dataset.num_classes}
    finetune_keys: [model.head.weight, model.head.bias]
